### ISSUE TITLE
GUI GTK Tracer

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#3]
Gtk rs is mess, but still probably the only good solution for rich UI in Rust.
It require reading C code and documentation with C examples.

Todo
- [ ] - Saving and loading include/excluded directories/items at exit to config file
- [ ] - Settings tab
- [ ] - Translation support(Czkawka should have multilingual interface)
- [ ] - GTK 4 support  #12
- [ ] - Light theme support #14
- [x] - Don't lock UI when searching, because user thinks that app freeze #34
- [ ] - Save and load settings from and to file #28
- [ ] - Add saving file dialog, to choose proper file name #26

**Comment by qarmin** [comment]
I'm to lazy to update this
