### ISSUE TITLE
Core of Czkawka Tracker

### ISSUE THREAD

**Issue by qarmin** [qarmin/czkawka#50]
- [ ] - Duplicate finder should only create hash of files until found difference between them #49
- [ ] - Finding files with debug symbols #7
- [ ] - Windows/MacOS support(macos is probably supported but it needs to be tested) #11
- [x] - Find zeroed files #20
- [ ] - Support for different types of hashes #22
- [ ] - Cache support #23
- [ ] - Temporary files, support for removing folder content like #25
- [x] - Multi thread support of file hasher(and also other things) #24
- [ ] - Check only local file system #31 
- [x] - Add support for universal excluded items and directories for CLI and GUI

**Comment by qarmin** [comment]
I'm to lazy to update this
